# http服务启动端口
port: 8899

proxyConfig:
  - desc: "订阅转换服务"
    paths: # URL中PATH 不包含参数 。 可以配置多个
      - path: "/sub"        # URL中PATH 不包含参数 。 可以配置多个
        matchType: "exact"  # paths匹配模式, exact：精确匹配、prefix：前缀匹配、regexp：正则匹配
        remove: ""          # 去除字符串，在请求之前，将请求URL中PATH的path去掉改字符串
      - path: "/version"
        matchType: "exact"
      - path: "/readconf"
        matchType: "exact"
      - path: "/updateconf"
        matchType: "exact"
      - path: "/getruleset"
        matchType: "exact"
      - path: "/getprofile"
        matchType: "exact"
      - path: "/qx-script"
        matchType: "exact"
      - path: "/qx-rewrite"
        matchType: "exact"
      - path: "/render"
        matchType: "exact"
      - path: "/convert"
        matchType: "exact"
      - path: "/getlocal"
        matchType: "exact"
    hosts: # 要并发访问的host
      - host: "https://api.tsutsu.cc"
        weight: 1
      - host: "https://sub.xeton.dev"
        weight: 1
      - host: "https://api.dler.io"
        weight: 1
      - host: "https://api.v1.mk"
        weight: 1
    filter:
      timeOut: 5000     # 超时时间 单位毫秒
      limitQps: 20      # 限流器，每秒只允许limiterQps访问,超过就
      limitHosts: 3     # 如果hosts数量过多，则随机选limit个进行请求
      limitRespHeaders: # 要过滤掉的响应头header，大小写敏感
        - "Set-Cookie"

  - desc: "百度"
    paths: # URL中PATH 不包含参数 。 可以配置多个
      - path: "/img/"
        matchType: "prefix"
      - path: "/www.baidu.com"
        matchType: "prefix"
        remove: "/www.baidu.com"
    hosts: # 要并发访问的host
      - host: "https://www.baidu.com"
        weight: 1
    filter:
      timeOut: 5000     # 超时时间 单位毫秒
      limitQps: 20      # 限流器，每秒只允许limiterQps访问,超过就
      limitHosts: 3     # 如果hosts数量过多，则随机选limit个进行请求
      limitRespHeaders: # 要过滤掉的响应头header，大小写敏感
        - "Set-Cookie"
